// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvzxanabydogfnorrkzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2enhhbmFieWRvZ2Zub3Jya3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODgwNzUsImV4cCI6MjA2MTE2NDA3NX0.Mr4K9CSky30cY85671QszQwgRelNWGvVGs4DPvq5AsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);